### ISSUE TITLE
SetAutoIndex(true) doesn't work with RenderHTML()

### ISSUE THREAD

**Issue by 8do** [jedib0t/go-pretty#108]
Hi, I'm newcomer to this package. And I just found that for the same table with `t.SetAutoIndex(true)` setting, `t.Render()` returned the rendered with auto index as expected, but `t.RenderHTML()` didn't.
Do you guys know why? Or did I do anything incorrect?

**Comment by jedib0t** [comment]
It is a bug. Auto-index is not being handled in RenderCSV/RenderHTML/RenderMarkdown. Will fix in a few days.

**Comment by 8do** [comment]
@jedib0t Thanks!

**Comment by jedib0t** [comment]
Hey @8do ... I've supported auto-index on CSV/HTML/Markdown modes. Thanks for bringing this up. The fix is available in the master branch and on tag `v5.0.1`.

Please note that I've removed some deprecated interfaces as of `v5.0.0` and you may have to migrate to the new interfaces to use `v5.x.x`. Check the [Release Notes](https://github.com/jedib0t/go-pretty/releases) page for details.

**Comment by 8do** [comment]
Thanks! Let me try and get back to you later.

**Comment by 8do** [comment]
@jedib0t I upgraded to `v6.0.0`, and it works now. But the footer row got Index=1 as well, can you please remove that?

<img width="38" alt="屏幕截图 2020-05-16 15 27 19" src="https://user-images.githubusercontent.com/65054513/82113628-1150a400-978a-11ea-80c4-76edd4bdea1b.png">

**Comment by jedib0t** [comment]
Fixed in this release: https://github.com/jedib0t/go-pretty/releases/tag/v6.0.1
