### ISSUE TITLE
v5.x does not work with `go mod`

### ISSUE THREAD

**Issue by jedib0t** [jedib0t/go-pretty#115]
**Describe the bug**
The `go mod` utility expects major versioning to be defined in the import paths and in the `go.mod` file. This is not done right, and hence `go get -u github.com/jedib0t/go-pretty@v5.0.1` does not work.

**To Reproduce**
In a new repo using `go mod`, try running `go get -u github.com/jedib0t/go-pretty@v5.0.1`.

**Expected behavior**
The code from `v5.0.1` is used and `go.mod` file refers to it.

**Additional context**
https://blog.golang.org/v2-go-modules

**Comment by jedib0t** [comment]
Workaround until this is fixed:
`go get -u github.com/jedib0t/go-pretty@8b58fba` <-- current latest commit on `master`

Or:
`go get -u github.com/jedib0t/go-pretty@master`

**Comment by jedib0t** [comment]
@xitonix I'm tracking the versioning bug here. I've shared a workaround above until this is fixed.

The final fix will involve changing your import paths in all the files you use any library from `go-pretty`. Will share details in the base README.md once available.

**Comment by xitonix** [comment]
Yep! The import paths need to be updated for sure mate. All good. Thank for keeping me in the loop buddy. 👍

**Comment by jedib0t** [comment]
@xitonix Please use `v6.0.0`. You'll have to change the import paths as directed at https://github.com/jedib0t/go-pretty#a-note-about-v600-and-above-

**Comment by 8do** [comment]
Cool! I tried to upgrade but failed.

**Comment by xitonix** [comment]
Hi @jedib0t,

If you want to maintain multiple versions side-by-side, you have two options:
- Duplicate the source code in a folder named after your version (v6 folder for example)
OR
- Keep your work in separate branches (v6 branch in this case)
I personally prefer the later, because I don't like the idea of duplicating the source code multiple times. 

Obviously the `go.mod` file in your `v6` branch will look like this:

```
module github.com/jedib0t/go-pretty/v6
```

And the one in master will be:

```
module github.com/jedib0t/go-pretty
```
Looking at your `go.mod` file in master though, I believe this is not your intention, which means you don't want to run multiple versions side-by-side. In that case, you need to `go get` the `v6` version in order to be able to fetch the latest release of the current stream:

```
go get github.com/jedib0t/go-pretty/v6
```

If you run `go get github.com/jedib0t/go-pretty@v6.0.2` for example, go mod won't be able to find `/v6` in the first place because it actually doesn't exist.

P.S: I would personally forget about keeping compatibility with `dep` or any other legacy dependency management solutions and make `go mod` the only citizen. But that's my personal opinion. 😉

**Comment by jedib0t** [comment]
Hey @xitonix ... I did decide to drop `dep` compatibility for now - if you look at the `dep` repo, the situation is really bad. If someone wants fixes back-ported, I've got a `v5` branch off which I can release `v5.x.x` patch releases, but I hope I don't have to do it.

And yes, you've to run one of the following to get the new code:
```
go get github.com/jedib0t/go-pretty/v6
go get github.com/jedib0t/go-pretty/v6@v6.0.2
```
