### ISSUE TITLE
Multiple progress writers

### ISSUE THREAD

**Issue by till** [jedib0t/go-pretty#150]
**Describe the bug**

Unclear to me how to use multiple progress writers. Not sure if bug or usage on my end.

It seems that once the first writer is autostopped (as its attached trackers finished), the next writer won't be started/rendered, etc.. I have a few cases where I may need to create trackers, at the time of creating the first writer, it's unclear how many more trackers I need "later" in the process. So I opted for multiple writers, also to be able to customize them a bit to fit better into what they are tracking.

I am trying to figure out if it's due to being a pointer, and really I am referencing the same again, somehow `go pw.Render()` doesn't initialize it. But I haven't had much luck figuring out what it is exactly.

```golang
func CreateTracker(message string, length int64) *progress.Tracker {
	unit := &progress.UnitsDefault

	tracker := progress.Tracker{
		Message: message,
		Total:   length,
		Units:   *unit,
	}

	return &tracker
}

func CreateWriter(numberOfTrackers int) progress.Writer {
	pw := progress.NewWriter()
	pw.SetAutoStop(true)
	pw.SetTrackerLength(20)
	pw.ShowETA(false)
	pw.ShowOverallTracker(false)
	pw.ShowTime(true)
	pw.ShowTracker(true)
	pw.ShowValue(false)
	pw.SetMessageWidth(50)
	pw.SetNumTrackersExpected(numberOfTrackers)
	pw.SetSortBy(progress.SortByPercentDsc)
	pw.SetStyle(progress.StyleDefault)
	pw.SetTrackerPosition(progress.PositionRight)
	pw.Style().Colors = progress.StyleColorsExample
	pw.Style().Options.PercentFormat = "%4.1f%%"

	return pw
}
```

That's the code I use to bootstrap your's.

**Comment by till** [comment]
I tried a few things today:

 - It seems to work more reliably when I stop using `SetAutoStop(true)` and implement logic around `Stop()`.
 - I used a "global" progress tracker and keep resetting it with `SetNumTrackersExpected()` 

Now, some of my output is out of order though. ;) Do you have any thoughts on how this will play nice with regular output written to `stdout`?

**Comment by jedib0t** [comment]
~~Did you take a look at the demo code at https://github.com/jedib0t/go-pretty/tree/master/cmd/demo-progress?~~

Nvm, looks like you might have seen it already.

> It seems that once the first writer is autostopped (as its attached trackers finished), the next writer won't be started/rendered, etc.. I have a few cases where I may need to create trackers, at the time of creating the first writer, it's unclear how many more trackers I need "later" in the process. So I opted for multiple writers, also to be able to customize them a bit to fit better into what they are tracking.

In case of not knowing how many trackers you will add in the process, it is better to NOT use AutoStop. It might make a lot more sense to control the progress writer completely from your end and call Stop() when you are sure you want to stop.

> I used a "global" progress tracker and keep resetting it with SetNumTrackersExpected()

While I've tried to make it work in global scope as much as I can, I wouldn't recommend it. Up to you though!

> Do you have any thoughts on how this will play nice with regular output written to stdout?

:( Nope. Don;t think it will cause the progress writer is basically making assumptions on how many lines have been rendered, and uses ANSI escape sequences to move the cursor up a certain number of lines, erasing each line along the way. Then it just renders all the active trackers afresh. This all happens in a loop, and if anything is printed to stdout in between, it may not show up because this logic erases it too fast, or it might mess up the tracker rendering in subtle ways.

**Comment by till** [comment]
When I said global, I meant, I add it to my factory and re-use this instance throughout. So that seems to work nicely indeed.

Trying to figure out what else can be done to align your lib with other output. I get that it may not work right now, but do you have any thoughts on what could be done?

Anyway, this is a very nice lib and thank you for taking the time to respond! 🙏

**Comment by jedib0t** [comment]
Not at the moment no. I'll leave this open just in case I can think of something,
