### ISSUE TITLE
Allow column to bleed to the right into empty columns to the right (spreadsheet-style)

### ISSUE THREAD

**Issue by rfay** [jedib0t/go-pretty#183]
**Describe the bug**

I don't know that this is a bug or a support request or a feature request, but I'd like to be able to have the content of a cell fill the rest of the row to the right if the columns to the right are empty, as spreadsheets have always done by default.

Like spreadsheet cell B3 does here:

<img width="574" alt="Untitled_spreadsheet_-_Google_Sheets" src="https://user-images.githubusercontent.com/112444/130336534-48b19ea4-1c36-4c10-9888-226b6407c532.png">

Is there a way to do that? 

What I'm working on is so simple that I'm happy to change the number of columns on the fly as well, but haven't been able to figure out how to do that without breaking things, but that would work fine as well, if I could just change from 4 cols to 2, for example, and have the second column fill the space that columns 2-3-4 had.

Thanks for your help!

**Comment by jedib0t** [comment]
Hey @rfay ... this cannot be supported at the moment because of the rudimentary implementation of the table rendering logic. I'd originally started working on an alternate approach a year or so back, and never found the time to go back to it as it involved changing a lot of the underlying logic. I'll try to see if I can find some spare time to start back that effort to support such a use-case.

For now, you could theoretically try using the Auto-Merge feature (https://github.com/jedib0t/go-pretty/tree/main/table#auto-merge) and make the three columns contain the same data and get it auto-merged.

**Comment by rfay** [comment]
Thanks - yeah, I tried the auto-marge, but it didn't result in reasonable behavior at all.

**Comment by jedib0t** [comment]
@rfay I need to rework the auto-merge feature. I feel I implemented it badly.

**Comment by rfay** [comment]
I hope you'll mention here when you have progress. I'll subscribe to release notifications as well.

Thanks for your work on this!
