### ISSUE TITLE
tables: Prevent wrapping on non-wrappable character

### ISSUE THREAD

**Issue by rfay** [jedib0t/go-pretty#191]
**Is your feature request related to a problem? Please describe.**

I use go-pretty for tables that describe [ddev](https://github.com/drud/ddev) projects. For example:

```
$ ddev list
detected terminal width=76 usableWidth=61 statusWidth=7 nameWidth=10 typeWIdth=7 locationWidth=20 urlWidth=20 totUsedWidth=64
┌────────┬─────────┬──────────────────────┬──────────────────────┬─────────┐
│ NAME   │ TYPE    │ LOCATION             │ URL                  │ STATUS  │
├────────┼─────────┼──────────────────────┼──────────────────────┼─────────┤
│ d9     │ drupal9 │ ~/workspace/d9       │                      │ stopped │
├────────┼─────────┼──────────────────────┼──────────────────────┼─────────┤
│ junk   │ php     │ ~/work/ddev/ddev/jun │ http://junk.ddev.sit │ running │
│        │         │ k                    │ e                    │  (ok)   │
├────────┼─────────┼──────────────────────┼──────────────────────┼─────────┤
│ Router │         │ healthy              │                      │         │
└────────┴─────────┴──────────────────────┴──────────────────────┴─────────┘
```

The feature request would be to have a way to prevent wrapping of things that make a mess when they wrap. The example would be the "location" and URL cells on the "junk" project here. I often need to copy/paste those, and the wrap just makes that impossible

**Describe the solution you'd like**

Have an option to prevent wrapping on non-space/tab/whatever characters

**Describe alternatives you've considered**

**Additional context**

**Comment by jedib0t** [comment]
Hey @rfay!

I'm guessing your code works something like this:
```golang
	tw := table.NewWriter()
	tw.AppendHeader(table.Row{"Name", "Type", "Location", "URL", "Status"})
	tw.AppendRow(table.Row{"d9", "drupal9", "~/workspace/d9", "", "stopped"})
	tw.AppendRow(table.Row{"junk", "php", "~/work/ddev/ddev/junk", "http://junk.ddev.site", "running (ok)"})
	tw.AppendRow(table.Row{"Router", "", "", "", "healthy"})
	tw.SetColumnConfigs([]table.ColumnConfig{
		{Name: "Location", WidthMax: 20},
		{Name: "URL", WidthMax: 20},
		{Name: "Status", WidthMax: 7},
	})
	tw.SetOutputMirror(os.Stdout)
	tw.Render()
```

Since your column is know to have URLs, I'd recommend one of the following:
1. Don't enforce a max width since you never want a URL to be cut off
2. If you think you'll have a URL and text, then don't enforce a max width, but introduce a new line after the URL using something like `strings.Replace(url, " ", "\n", 1) // watch out for spaces in the URL itself` --- this will ensure all non-URL text goes to the next line
3. Or set a higher WidthMax value than 20 and use text.WrapSoft like so: `{Name: "URL", WidthMax: 64, WidthMaxEnforcer: text.WrapSoft}` - however if the URL is longer than 64 chars in this case, you'll run into the same issue

I think logically solution 1 should be the preferred approach, but at the risk of making the table really long when the URLs are long. Honestly, URLs in tables have been an issue I don't think we can really solve since ultimately the terminal width will screw up how it gets displayed.

**Comment by rfay** [comment]
Thanks so much for the suggestions, I'll give it a go.
