### ISSUE TITLE
Setting the MessageWidth to 40 caused incorrect progress output

### ISSUE THREAD

**Issue by ykoehler** [jedib0t/go-pretty#194]
**Describe the bug**
I modified cmd/demo-progress/demo.go to use SetMessageWidth(40) and the progress stop to work properly (display keep scrolling down)

**To Reproduce**
See above

**Expected behavior**
Expect same behavior as with < 40 MessageWidth.

**Screenshots**
![image](https://user-images.githubusercontent.com/2739855/158885607-7b254efc-d6a1-4b05-889f-9636bd789193.png)

**Software (please complete the following information):**
CentOS 7 Linux

**Additional context**

**Comment by jedib0t** [comment]
This happens if the terminal width is shorter than the output width. You can try with original size, and a less-wider terminal. This cannot be fixed from this library's perspective.

An alternate approach is to get the current terminal width and adjust the lengths of individual components to sum up to something less than the terminal width. Even in this case, you'd have to watch and account for dynamic terminal resizes.

**Comment by jedib0t** [comment]
Closing this bug for now due to lack of response.
