### ISSUE TITLE
Quite poor documentation

### ISSUE THREAD

**Issue by wauxhall** [jedib0t/go-pretty#205]
Most docs refer to "go and read the code", that's time-consuming and very annoying, especially when you find out that it's not what you were looking for.
No example usages for text package. Fix it please.

**Comment by jedib0t** [comment]
Doesn't this have enough documentation for text: https://pkg.go.dev/github.com/jedib0t/go-pretty/v6@v6.3.1/text

If not can you describe what is missing?

**Comment by jedib0t** [comment]
@wauxhall Please check the comment above. I'll close this issue if I don't hear back in a week. Thanks!

**Comment by Thijxx** [comment]
Could this please be reopened in order to get some examples for the usage of `text` like there are for `table` and `list`?
I looked at the link @jedib0t provided and it contains no examples like there are for `list` for example. What is missing, as the  OP wrote, is examples.

- https://github.com/jedib0t/go-pretty/tree/main/cmd/demo-list
- https://github.com/jedib0t/go-pretty/tree/main/cmd/demo-table
- https://github.com/jedib0t/go-pretty/tree/main/cmd/demo-progress

Next to `/cmd/demo-list` and `/cmd/demo-progress` and `/cmd/demo-table` there could be a `demo-text` demonstrating the possibilities and showing a function example. The demo's for `list` and `table` are great so those are a good example.

**Comment by jedib0t** [comment]
> I looked at the link @jedib0t provided and it contains no examples like there are for `list` for example. What is missing, as the  OP wrote, is examples.

There is a whole section called Examples in that link, for every utility function in text.

Here is the section I'm talking about:
![image](https://github.com/user-attachments/assets/ada6f257-bc44-4e5b-aa41-02ee0afe4ce6)

Here is the examples section for `RepeatAndTrim` (one of the many functions with examples):
![image](https://github.com/user-attachments/assets/ccf25009-30f7-49d0-919d-5fc2bb906510)

What do you think is missing in the examples?

The other packages have detailed demos because those need proper set up before usage and are not single function calls. Whereas the `text` package is just utility functions that don't need elaborate set up before usage, and the examples in GoDoc cover every function.
