### ISSUE TITLE
Printing new table rows after render

### ISSUE THREAD

**Issue by trietsch** [jedib0t/go-pretty#249]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to print new table rows after the initial data is rendered in the table. Potential footers are irrelevant for me in this case, as new data should be added in the data section of the table as it arrives.

**Describe the solution you'd like**
See above.

**Describe alternatives you've considered**
I'm not sure whether this is supported at the moment. Had a look at the API, but I can't find anything for this.

**Comment by jedib0t** [comment]
This won't work due to edge cases, for example, what if a column in the new row is longer than the longest value seen till now - making the alignment not work.

A workaround I can recommend:
1. Print the table, keep track of the number of lines printed (say X)
2. Append the rows to the table
3. Use [cursor.go](https://github.com/jedib0t/go-pretty/blob/main/text/cursor.go) functionality to print CursorUp and EraseLine X number of times ([usage here](https://github.com/jedib0t/go-pretty/blob/main/text/cursor_test.go))
4. Go to Step 1

This will work relatively well for tables that doesn't have 100s of rows. If you have more, you can always work a logic to rebuild the table with the last X rows and just print a limited number of rows during every refresh.

**Comment by jedib0t** [comment]
Closing due to lack of response.

**Comment by trietsch** [comment]
@jedib0t sorry for the late reply. Thanks for the workaround, went with a similar approach :)
